ANGLE_COLUMNS_MAPPING = {
    11: 'angle_underarm_l',
    12: 'angle_underarm_r',
    13: 'angle_elbow_l',
    14: 'angle_elbow_r',
    23: 'angle_waist_l',
    24: 'angle_waist_r',
    25: 'angle_knee_l',
    26: 'angle_knee_r'
}
COLUMNS_NAME_MAPPING = {
    7: "ear_l",
    8: "ear_r",
    11: 'shoulder_l',
    12: 'shoulder_r',
    13: 'elbow_l',
    14: 'elbow_r',
    15: 'wrist_l',
    16: 'wrist_r',
    23: 'waist_l',
    24: 'waist_r',
    25: 'knee_l',
    26: 'knee_r',
    27: 'ankle_l',
    28: 'ankle_r',
}

COLUMNS = [
    'datetime',
    'angle_elbow_r', 
    'angle_elbow_r_start_angle', 
    'angle_elbow_r_end_angle', 
    'angle_elbow_l', 
    'angle_elbow_l_start_angle', 
    'angle_elbow_l_end_angle', 
    'angle_underarm_l', 
    'angle_underarm_l_start_angle', 
    'angle_underarm_l_end_angle', 
    'angle_underarm_r', 
    'angle_underarm_r_start_angle', 
    'angle_underarm_r_end_angle', 
    'angle_waist_r', 
    'angle_waist_r_start_angle', 
    'angle_waist_r_end_angle', 
    'angle_waist_l', 
    'angle_waist_l_start_angle', 
    'angle_waist_l_end_angle', 
    'angle_knee_r', 
    'angle_knee_r_start_angle', 
    'angle_knee_r_end_angle', 
    'angle_knee_l', 
    'angle_knee_l_start_angle', 
    'angle_knee_l_end_angle', 
    'width_elbow_shoulder_r', 
    'width_elbow_shoulder_l', 
    'dist_height_r', 
    'dist_height_l', 
    'dist_width', 
    'height_shoulder_waist_r', 
    'height_shoulder_waist_l', 
    'height_waist_knee_r', 
    'height_waist_knee_l', 
    'height_knee_shoulder_r', 
    'height_knee_shoulder_l', 
    'height_ankle_waist_r', 
    'height_ankle_waist_l', 
    'shoulder_l_r', 
    'waist_l_r', 
    'knee_l_r', 
    'img_w', 
    'img_h',
    'visibility_ear_l', 
    'visibility_ear_r', 
    'visibility_shoulder_l', 
    'visibility_shoulder_r', 
    'visibility_elbow_l', 
    'visibility_elbow_r', 
    'visibility_wrist_l', 
    'visibility_wrist_r', 
    'visibility_waist_l', 
    'visibility_waist_r', 
    'visibility_knee_l', 
    'visibility_knee_r', 
    'visibility_ankle_l', 
    'visibility_ankle_r',
    'label'
]